### ISSUE TITLE
Sprig in control panel

### ISSUE THREAD

**Issue by jamiematrix** [putyourlightson/craft-sprig#137]
### Question
Is it possible to use Sprig within the admin side of a Craft site?

### Additional context
I have a page to generate reports (made 100% better using Sprig), but I'd like it to be a page within the admin cp. I can add the basic markup, but when I get to adding the Sprig component I get an error of file not found. I have copied the component to just about every folder I can think it may be looking in, but have had no joy.

**Comment by bossanova808** [comment]
After a long gap in working on Craft stuff, and then getting back in to module development, I ran in to this same issue - I just couldn't seem to get sprig to load up templates no matter where I put them.  Drove me nuts.

I had forgotten the one key thing - in plugins/modules, the template path must be preceded by the module name as a pointer to where to find the templates folder in this context.

From the docs: https://craftcms.com/docs/3.x/extend/cp-templates.html#page-templates - it's just kind of hidden in the text there but it's really important:

```
Plugins can define templates within the templates/ folder within their base source folder. 
Templates within there can be referenced using the plugin’s handle as the template path prefix.
```

As an example, I have a module named `bridge`, and I have a folder in it for templates, with a sub-folder for sprig components, so from the Craft root directory it looks like this on disk:

`/modules/bridge/templates/stock.twig`  (parent template that loads the sprig component)

`/modules/bridge/templates/_sprig_components/stock-check.twig`  (the actual twig component)

in the main module file (Bridge.php), I define a nav item:

```
        Event::on(
            Cp::class,
            Cp::EVENT_REGISTER_CP_NAV_ITEMS,
            static function(RegisterCpNavItemsEvent $event) {
                $event->navItems[] = [
                    'url' => 'bridge/stock',
                    'label' => 'Check Stock Levels',
                    'icon' => '@modules/site/assets/dist/is_glyph.svg',
                ];
      )
```

(note the URL here is `module_name`/`template_name` - without the `templates` folder that is actually in the physical path, this is the bit I always get confused about...but there's 'magic' that means it looks in the `templates` folder when given this path...)

Then in `/modules/bridge/templates/stock.twig` I actually call on sprig to load and make the component reactive (actually a few components):

```
{% extends '_layouts/cp' %}
{% set title = 'Stock Check' %}
{% block toolbar %}
    <div class="toolbar-wrapper">
        {{ sprig('bridge/_sprig_components/toolbar-actions') }}
        {{ sprig('bridge/_sprig_components/toolbar-cache-tracker') }}
    </div>
{% endblock %}
{% block content %}
    {{ sprig('bridge/_sprig_components/stock-check') }}
    {# Has to be inside a block, might as well be here... #}
    {{ sprig.script }}
{% endblock %}
```

Again, note the 'magic' of using the `module_name` (ie `bridge`) - and NOT using the `templates` folder,  and then using the sub folder that has your components in it, so that:

Physical path:
`/modules/bridge/templates/_sprig_components/stock-check.twig` 

Reference in your module:
` {{ sprig('bridge/_sprig_components/stock-check') }}`


(Personally I find magic like that rather irritating and wish that using the module name just pointed things at the module root folder, rather than this implicit (and english centric) reference to `templates`, but....that's how it works...I presume so that it is very clear as to what will be web accessible and what won't).

In terms of the actual templates, from there it should be like any other control panel template, or really any template in Craft.  (And I'll just add the dev experience of using Sprig to build CP things is just glorious - you can add so much useful functionality so quickly!).

Hopefully I am not making an incorrect assumption as to what your problem is - if so, can you post some code?

**Comment by bencroker** [comment]
Thanks for responding @bossanova808!
