### ISSUE TITLE
Switch to using requests that accept JSON

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-sprig#301]
Requests that accept JSON responses should be used when running controller actions, in order to simplify and add resilience to the handling of responses. This is already required in some special cases such as https://github.com/putyourlightson/craft-sprig/issues/300, however will introduce breaking changes and should therefore be part of v3.

**Comment by bossanova808** [comment]
This is interesting to see.  It's always confused me a little that Sprig didn't work this way from the start - i.e. controllers just returning JSON to the templates, and the templates then render the HTML, with that then going over the wire, as per the HTMX ethos.

(It would be great, actually, if the Sprig docs had a section on the right way to build controllers for use with Sprig - would have really helped me when getting started with Sprig!).

To be honest, when I saw this in Craft 4's upgrade notes:
https://craftcms.com/docs/4.x/extend/updating-plugins.html#controller-responses

```
Controller actions can return new ..asSuccess etc ...functions that automatically handle:
...
returning relevant model data in the JSON response or route params
```

...I interpreted that one would simply be able to do this:

`return $this->asSuccess("success", $dataArray);`

...and that (i.e. Craft) would then automatically set the route params, and those would therefore be available in the templates.  I realise, reading it more carefully, it's probably only talking about controller actions like `save` on a model or similar, rather than the general case.  

So at the moment, one still has to:

```
        Craft::$app->getUrlManager()->setRouteParams($dataArray);
        return $this->asSuccess("success");
```

Am I right in thinking when this change comes, `return $this->asSuccess("success", $dataArray);` is all that will then be needed?

Also - is the idea that Sprig V3 will come with Craft 5, perhaps?  Or no real idea/ETA yet?  Just trying to factor in when I do some re-factoring work!

**Comment by bencroker** [comment]
Yes, you pretty much got it all right. The reason I held off on doing this in version 2 is that many plugins did not switch to using `asSuccess()`/`asModelSuccess()` or `asFailure()`/`asModelFailure()` immediately, meaning that this would have introduced seemingly random breaking changes. It is planned for v3 which will be released alongside Craft 5 and I plan on formalising some documentation for it at that stage.

**Comment by bossanova808** [comment]
Thanks for confirming, good to know my understanding is not off here!

I've been using those new return functions, but I find them oddly inconsistent (e.g. `asFailure` accepts a parameter for route params, but `asSuccess` does not?!) - I supect/hope there will be some improvement of those with C5, so absolutely makes sense to wait.

(I find the whole issue of controller returns a bit vexed...e.g. is a _handled_ error a success or a failure return?  Is no results a success?  Should there _always_ be a `message`, if so what, and/or should one rely completely on status codes?  The whole area feels like it is in a bit of a messy transition right now - I'm finding it near impossible to be consistent across various controllers!).

**Comment by bencroker** [comment]
I know what you mean, it likely has a lot to do with avoiding breaking changes in Craft. Perhaps that’s an area of improvement you could suggest for Craft 5.

**Comment by bencroker** [comment]
Unfortunately, it doesn‘t look like this switch can happen. I started implementing it, but then realised that the model is converted to an array in the data that is sent back in the JSON response, making it much less useful to work with.
https://github.com/craftcms/cms/blob/97b108a09d2798deb43a9132d764cea4ca9195e0/src/web/Controller.php#L398

So it looks like the current method of doing things (along with a few special cases) is going to have to stay.
