### ISSUE TITLE
`sprig.script` doesn't honour resourceBaseUrl setting

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-sprig#326]
It seems that `{{ sprig.script }}` doesn't fetch the needed script from the URL specified with the parameter `resourceBaseUrl`, which is set in `/config/custom.php`. Instead, it fetches the script from the Base URL – which leads to a 404 error in our Live setup, in which the Resource Base URL and the Site URL differ from each other.

- Craft: 4.55
- Sprig: 2.6.2

**Comment by bencroker** [comment]
The `{{ sprig.script }}` tag outputs a path to the script that is published in the `cpresources` folder. What exactly are you seeing?

**Comment by martinhellwagner** [comment]
I'm seeing `https://www.domain.com/cpresources/.../htmx.min.js` (example) while I was expecting to see `https://assets.domain.com/cpresources/.../htmx.min.js`, since `https://assets.domain.com` is what the Resource Base URL is set to.

**Comment by bencroker** [comment]
Craft determines the path to the `cpresources` folder, not Sprig. The decision was made to put the script in the `cpresources` folder rather than setting a new convention for where plugin assets should be written to. If you want to load it from a custom location then you can replace `{{ sprig.script }}` with your own `<script>` tag pointing to a local copy of the script or a CDN URL (`<script src="https://unpkg.com/htmx.org@1.9.5">`). 

Note that this behaviour is changing in the upcoming version of Sprig, see https://github.com/putyourlightson/craft-sprig-core/blob/8b621d7138c2c5c21beb71b6b16059184d0e3a84/CHANGELOG.md?plain=1#L13

**Comment by martinhellwagner** [comment]
Thanks for the clarification! I'll be using the direct path to the `html.min.js` file until Sprig 2.6.0 is released. Do you have a rough timing on this release?

**Comment by bencroker** [comment]
Aiming for next week.

**Comment by martinhellwagner** [comment]
@bencroker 

Great, thanks!
