### ISSUE TITLE
Filter reset button

### ISSUE THREAD

**Issue by Shanyb** [putyourlightson/craft-sprig#343]
I created, with Sprig, filters for the entries. I need, each time we activate a filter, an additional button to be created indicating that this filter is selected. Also, this same button would allow you to delete this individual filter. A kind of filter reset.

It seems difficult to synchronize two elements performing the same action.

Do you have any leads on this?

**Comment by bencroker** [comment]
This sounds similar to the reset button for the product filters used in the [Sprig Filters component](https://putyourlightson.dev/sprig/components/filters), except that rather than clear all filters, it only clears the relevant filters. Namespacing the buttons should allow you to achieve that.

I explain how the component is built in the videos at https://putyourlightson.com/sprig/videos#sprig-filters
