### ISSUE TITLE
Need precisions about deprecated flash message following 2.8.0 update

### ISSUE THREAD

**Issue by romainpoirier** [putyourlightson/craft-sprig#358]
Following the update to version `2.8.0`, the release notes mentioned:

> Deprecated the flashes variable. Use sprig.message or craft.app.session.flash() instead.

However, after updating, when trying to retrieve flash messages, I get the results as follows:

- `flashes | default([])` successfully returns the expected result.
- `sprig.message | default(null)` doesn't return any result.
- `craft.app.session.flash('myFlashKey')` doesn't return any result.

Here's how I'm setting the flash message in my Controller at the end of the script:
`return Craft::$app->session->setFlash("myFlashKey", "My flash message");`

Is flashes still a valid method for setting flash messages after the `2.8.0` update?
Despite the deprecation, can I still reliably retrieve responses via the `flashes` method?
If no, how can I make the new recommended methods working?

**Comment by bencroker** [comment]
`flashes` will continue to work but will be removed in Sprig 3 (for Craft 5), so it is better to stop using it, if possible. 

`sprig.message` will output either the `success` or `error` flash message, depending on whether the response is successful. 

`craft.app.session.flash` will not work, since flash messages are removed after being accessed – that was my error in the changelog.

As I see it, your options are:
1. Use the `asSuccess` and `asFailure` methods in your controller.
```php
if ($success) {
    return $this->asSuccess($message);
}
return $this->asFailure($message);
```
2. Use the `setSuccessFlash` and `setFailFlash` methods in your controller.
```php
if ($success) {
    $this->setSuccessFlash($message);
} else {
    $this->setFailFlash($message);
}
```
3. If you must use your own key, then put it in a session, which will persist for more than one request and which you can retrieve with `craft.app.session.get('myFlashKey')`.
```php
Craft::$app->getSession()->set('myFlashKey', $message);
```
