### ISSUE TITLE
2 forms inside a Sprig Component

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-sprig#66]
### Question
I am having two forms inside a sprig component but when I submit 1 of the forms its kind of  submitting both of them. Its only doing 1 XHR request but it is submitting data from both forms. Is that due to wrong setup by me?

### Additional context

So I am outputting this form below for every item in a Commerce cart which is a sprig component. It's to remove the line item. Trying to remove Alpinejs ajax call with Sprig. (Wether that is smart is another matter :) )

For some reason my form code is being stripped so here is a screenshot. https://share.getcloudapp.com/Kouleejd

As you can see here https://share.getcloudapp.com/RBu9XXyy it does 1 ajax request but with 2 lines of **lineItems** data so it removes both items when submitting 1 form.

**Comment by bencroker** [comment]
This is happening because by default, all input fields inside of a Sprig component are submitted in the request. Since you just have a single button, I would simplify the code by replacing the form with the following;

```twig
{% set vals = {('lineItems[' ~ item.id ~ '][remove]'): 1}|json_encode %}
<button sprig s-action="commerce/cart/update-cart" s-method="post" s-vals="{{ vals }}" s-confirm="Are you sure you want to remove this product from your cart?">
    Remove
</button>
```

Note that we are forced to use `s-vals` instead of `s-val:*` because `s-val:lineItems[0][remove]` is not a valid HTML attribute (because of the square brackets).

**Comment by philipboomy** [comment]
Lovely - Much smarter and it works. Thanks!
I tried researching a little bit so its nice to know that Sprig works like this as default.

Oh the power Sprig has.

Add to cart
Remove from cart
Product filtering

Now I need to add item-options and checkout. All while using Twig.
